from datetime import datetime
from pendulum import timezone

from airflow.models import DAG
from airflow.operators.bash import BashOperator
from airflow.utils.task_group import TaskGroup

        
with DAG(
    dag_id="soss_etl_once",
    start_date=datetime(2023, 8, 1, tzinfo=timezone("Asia/Seoul")),
    schedule_interval="@once",
    catchup=False,
    max_active_runs=1
) as dag:

    cmd_list = [
        "/root/anaconda3/bin/python /root/migration/insert_dw_cn_pcell_tmzn_fpop.py boryeong_si 01",
        "/root/anaconda3/bin/python /root/migration/insert_dw_cn_pcell_tmzn_fpop.py boryeong_si 02",
        "/root/anaconda3/bin/python /root/migration/insert_dw_cn_pcell_tmzn_fpop.py boryeong_si 03",
        "/root/anaconda3/bin/python /root/migration/insert_dw_cn_pcell_tmzn_fpop.py boryeong_si 04",
        "/root/anaconda3/bin/python /root/migration/insert_dw_cn_pcell_tmzn_fpop.py boryeong_si 10",
        "/root/anaconda3/bin/python /root/migration/insert_dw_cn_pcell_tmzn_fpop.py boryeong_si 11",
        "/root/anaconda3/bin/python /root/migration/insert_dw_cn_pcell_tmzn_fpop.py boryeong_si 12",
        "/root/anaconda3/bin/python /root/migration/insert_dw_cn_pcell_tmzn_fpop.py nonsan_si 01",
        "/root/anaconda3/bin/python /root/migration/insert_dw_cn_pcell_tmzn_fpop.py nonsan_si 02",
        "/root/anaconda3/bin/python /root/migration/insert_dw_cn_pcell_tmzn_fpop.py nonsan_si 03",
        "/root/anaconda3/bin/python /root/migration/insert_dw_cn_pcell_tmzn_fpop.py nonsan_si 04",
        "/root/anaconda3/bin/python /root/migration/insert_dw_cn_pcell_tmzn_fpop.py gongju_si 01",
        "/root/anaconda3/bin/python /root/migration/insert_dw_cn_pcell_tmzn_fpop.py gongju_si 02",
        "/root/anaconda3/bin/python /root/migration/insert_dw_cn_pcell_tmzn_fpop.py gongju_si 03",
        "/root/anaconda3/bin/python /root/migration/insert_dw_cn_pcell_tmzn_fpop.py gongju_si 04",
        "/root/anaconda3/bin/python /root/migration/insert_dw_cn_pcell_tmzn_fpop.py seosan_si 01",
        "/root/anaconda3/bin/python /root/migration/insert_dw_cn_pcell_tmzn_fpop.py seosan_si 02",
        "/root/anaconda3/bin/python /root/migration/insert_dw_cn_pcell_tmzn_fpop.py seosan_si 03",
        "/root/anaconda3/bin/python /root/migration/insert_dw_cn_pcell_tmzn_fpop.py seosan_si 04",
        "/root/anaconda3/bin/python /root/migration/insert_dw_cn_pcell_tmzn_fpop.py seosan_si 10",
        "/root/anaconda3/bin/python /root/migration/insert_dw_cn_pcell_tmzn_fpop.py seosan_si 11",
        "/root/anaconda3/bin/python /root/migration/insert_dw_cn_pcell_tmzn_fpop.py seosan_si 12",
        "/root/anaconda3/bin/python /root/migration/insert_dw_cn_pcell_tmzn_fpop.py asan_si 01",
        "/root/anaconda3/bin/python /root/migration/insert_dw_cn_pcell_tmzn_fpop.py asan_si 02",
        "/root/anaconda3/bin/python /root/migration/insert_dw_cn_pcell_tmzn_fpop.py asan_si 03",
        "/root/anaconda3/bin/python /root/migration/insert_dw_cn_pcell_tmzn_fpop.py asan_si 04",
        "/root/anaconda3/bin/python /root/migration/insert_dw_cn_pcell_tmzn_fpop.py asan_si 10",
        "/root/anaconda3/bin/python /root/migration/insert_dw_cn_pcell_tmzn_fpop.py asan_si 11",
        "/root/anaconda3/bin/python /root/migration/insert_dw_cn_pcell_tmzn_fpop.py asan_si 12",
        "/root/anaconda3/bin/python /root/migration/insert_dw_cn_pcell_tmzn_fpop.py dangjin_si 01",
        "/root/anaconda3/bin/python /root/migration/insert_dw_cn_pcell_tmzn_fpop.py dangjin_si 02",
        "/root/anaconda3/bin/python /root/migration/insert_dw_cn_pcell_tmzn_fpop.py dangjin_si 03",
        "/root/anaconda3/bin/python /root/migration/insert_dw_cn_pcell_tmzn_fpop.py dangjin_si 04",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py gyeryong_si 01",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py gongju_si 01",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py geumsan_gun 01",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py nonsan_si 01",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py dangjin_si 01",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py boryeong_si 01",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py buyeo_gun 01",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py seosan_si 01",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py seocheon_gun 01",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py asan_si 01",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py yesan_gun 01",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py cheongyang_gun 01",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py taean_gun 01",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py hongseong_gun 01",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py cheonan_si_dongnam_gu 01",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py cheonan_si_seobuk_gu 01",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py gyeryong_si 02",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py gongju_si 02",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py geumsan_gun 02",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py nonsan_si 02",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py dangjin_si 02",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py boryeong_si 02",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py buyeo_gun 02",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py seosan_si 02",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py seocheon_gun 02",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py asan_si 02",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py yesan_gun 02",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py cheongyang_gun 02",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py taean_gun 02",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py hongseong_gun 02",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py cheonan_si_dongnam_gu 02",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py cheonan_si_seobuk_gu 02",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py gyeryong_si 03",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py gongju_si 03",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py geumsan_gun 03",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py nonsan_si 03",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py dangjin_si 03",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py boryeong_si 03",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py buyeo_gun 03",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py seosan_si 03",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py seocheon_gun 03",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py asan_si 03",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py yesan_gun 03",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py cheongyang_gun 03",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py taean_gun 03",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py hongseong_gun 03",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py cheonan_si_dongnam_gu 03",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py cheonan_si_seobuk_gu 03",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py gyeryong_si 04",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py gongju_si 04",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py geumsan_gun 04",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py nonsan_si 04",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py dangjin_si 04",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py boryeong_si 04",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py buyeo_gun 04",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py seosan_si 04",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py seocheon_gun 04",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py asan_si 04",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py yesan_gun 04",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py cheongyang_gun 04",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py taean_gun 04",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py hongseong_gun 04",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py cheonan_si_dongnam_gu 04",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py cheonan_si_seobuk_gu 04",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py gyeryong_si 09",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py gongju_si 09",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py geumsan_gun 09",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py nonsan_si 09",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py dangjin_si 09",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py boryeong_si 09",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py buyeo_gun 09",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py seosan_si 09",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py seocheon_gun 09",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py asan_si 09",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py yesan_gun 09",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py cheongyang_gun 09",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py taean_gun 09",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py hongseong_gun 09",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py cheonan_si_dongnam_gu 09",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py cheonan_si_seobuk_gu 09",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py gyeryong_si 10",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py gongju_si 10",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py geumsan_gun 10",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py nonsan_si 10",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py dangjin_si 10",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py boryeong_si 10",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py buyeo_gun 10",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py seosan_si 10",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py seocheon_gun 10",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py asan_si 10",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py yesan_gun 10",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py cheongyang_gun 10",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py taean_gun 10",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py hongseong_gun 10",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py cheonan_si_dongnam_gu 10",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py cheonan_si_seobuk_gu 10",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py gyeryong_si 11",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py gongju_si 11",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py geumsan_gun 11",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py nonsan_si 11",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py dangjin_si 11",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py boryeong_si 11",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py buyeo_gun 11",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py seosan_si 11",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py seocheon_gun 11",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py asan_si 11",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py yesan_gun 11",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py cheongyang_gun 11",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py taean_gun 11",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py hongseong_gun 11",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py cheonan_si_dongnam_gu 11",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py cheonan_si_seobuk_gu 11",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py gyeryong_si 12",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py gongju_si 12",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py geumsan_gun 12",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py nonsan_si 12",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py dangjin_si 12",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py boryeong_si 12",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py buyeo_gun 12",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py seosan_si 12",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py seocheon_gun 12",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py asan_si 12",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py yesan_gun 12",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py cheongyang_gun 12",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py taean_gun 12",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py hongseong_gun 12",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py cheonan_si_dongnam_gu 12",
        "/root/anaconda3/bin/python /root/migration/insert_dw_pcel_tmzn_fml_pop_sum.py cheonan_si_seobuk_gu 12",
    ] 

    tasks = []

    for cmd in cmd_list:

        cmd_info = cmd.split(" ")[-3].split(".")[0]
        gu_name = cmd.split(" ")[-2].strip()
        month = cmd.split(" ")[-1].strip()
        
        with TaskGroup(group_id=f"{gu_name}") as gu_task:
            # 안전지수 전처리
            gu_processing = BashOperator(
                task_id=f"{cmd_info}_{gu_name}_{month}",
                bash_command=str(cmd),
                trigger_rule="all_done"
            )
            
            gu_processing  

        tasks.append(gu_task)

    for i in range(len(tasks)-1):
        tasks[i] >> tasks[i+1]