#!/usr/bin/env python3
# -*- coding: utf-8-*-

import configparser
import os

config = configparser.ConfigParser()
config.read(os.path.join(os.path.dirname(os.path.abspath(__file__)), "config.ini"))

# POSTGRES_CONNECTION
DM_SERVER = config["POSTGRES_CONNECTION"]["DM_SERVER"]
DW_SERVER = config["POSTGRES_CONNECTION"]["DW_SERVER"]
POSTGRES_PORT = config["POSTGRES_CONNECTION"]["POSTGRES_PORT"]
POSTGRES_USER = config["POSTGRES_CONNECTION"]["POSTGRES_USER"]
POSTGRES_PASSWRD = config["POSTGRES_CONNECTION"]["POSTGRES_PASSWRD"]
POSTGRES_DB = config["POSTGRES_CONNECTION"]["POSTGRES_DB"]

# HDFS_CONNECTION
HDFS_HOST = config["HDFS_CONNECTION"]["HDFS_HOST"]
HDFS_PORT = config["HDFS_CONNECTION"]["HDFS_PORT"]

# PCELL
MIN_X_CRD = config["PCELL"]["MIN_X_CRD"]
MIN_Y_CRD = config["PCELL"]["MIN_Y_CRD"]

# SPARK_CONFIG
SPARK_MASTER = config["SPARK_CONFIG"]["SPARK_MASTER"]
SPARK_DRIVER_MEMORY = config["SPARK_CONFIG"]["SPARK_DRIVER_MEMORY"]
SPARK_EXECUTOR_MEMORY = config["SPARK_CONFIG"]["SPARK_EXECUTOR_MEMORY"]
SPARK_LOCAL_DIR = config["SPARK_CONFIG"]["SPARK_LOCAL_DIR"]
SPARK_MAX_RESULT_SIZE = config["SPARK_CONFIG"]["SPARK_MAX_RESULT_SIZE"]